### ISSUE TITLE
Doesn't show up in the connector's window.

### ISSUE THREAD

**Issue by beigexperience** [bgol/LandigPad#2]
E:D Market Connector says the plugin is loaded and the settings for the plugin show up in the config window, but when I'm landing the plugin isn't being drawn.

**Comment by bgol** [comment]
I guess it's an Ocellus Starport? The Stationtype was changed from bernal to ocellus.

A quick fix is to add the new type to the list in load.py line 31 to read like:
```python
this.show_types = ('bernal', 'coriolis', 'orbis', 'asteroidbase', 'ocellus')
```

You can test if the display works by writing `!pad 1` in the local chat. To clear the display write `!pad` (no number).
