### ISSUE TITLE
support "hiding" (or omitting) the EDMC window drawing when overlay is in use

### ISSUE THREAD

**Issue by slippycheeze** [bgol/LandigPad#5]
I use the EDMCOverlay option, to get the relevant position on my game screen, which is **great**, and very much appreciated.

I would be perfectly happy with nothing but the overlay, so from my perspective it'd be a fine thing if I could choose to omit the landing pad location in the EDMC window itself.   Basically, run in "overlay only" mode, as it were.

**Comment by bgol** [comment]
Good idea, but no timeframe for now.
