### ISSUE TITLE
thicker lines for overlay drawing

### ISSUE THREAD

**Issue by slippycheeze** [bgol/LandigPad#6]
the red and green lines of the station entrance are a bit difficult to see against some backgrounds, partly from colour, and partly because they are quite "thin" as such things go.

it'd be nice if there were an option to use heavier lines (aka 2-4 pixel height rectangles, I guess) to draw various parts of the overlay diagram.  especially for the entrance, but in general too, I guess.

**Comment by bgol** [comment]
I'll have to dig into EDMCOverlay again to see whats possible.

**Comment by bgol** [comment]
The EDMCOverlay does not offer different line thickness. I simulate it by drawing different sizes of the entrance. But this is too expensive for the station itself.
